apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab28-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SonHeung-min/Track2_Day28_2A202601327_OngXuanSon.git
    targetRevision: ca-nhan-ong-xuan-son
    path: deploy/kubernetes/base
  destination:
    server: https://kubernetes.default.svc
    namespace: lab28
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
